"""
Data Utilities Module
Handles catalog loading, sample data generation, and data preprocessing
"""

import pandas as pd
import numpy as np
from pathlib import Path
import random


def load_catalog() -> pd.DataFrame:
    """
    Load catalog items for similarity search
    In production, this would load from a database or FAISS index
    
    Returns:
        DataFrame with columns: item_id, description, image_path, embedding (optional)
    """
    # Create sample catalog items
    catalog_items = []
    
    # Sample item descriptions (Fashion-IQ style)
    sample_items = [
        {"item_id": "item_001", "description": "Vintage red denim jacket, button-down front", "category": "jacket"},
        {"item_id": "item_002", "description": "Blue cotton shirt, casual style", "category": "shirt"},
        {"item_id": "item_003", "description": "Black leather boots, excellent condition", "category": "shoes"},
        {"item_id": "item_004", "description": "White silk dress, formal evening wear", "category": "dress"},
        {"item_id": "item_005", "description": "Red denim jacket, vintage style, good condition", "category": "jacket"},
        {"item_id": "item_006", "description": "Green wool sweater, cozy and warm", "category": "shirt"},
        {"item_id": "item_007", "description": "Brown leather handbag, classic design", "category": "accessories"},
        {"item_id": "item_008", "description": "Blue jeans, slim fit, like new", "category": "pants"},
        {"item_id": "item_009", "description": "Red vintage top, retro style", "category": "shirt"},
        {"item_id": "item_010", "description": "Black formal blazer, professional attire", "category": "jacket"},
        {"item_id": "item_011", "description": "White cotton t-shirt, casual everyday", "category": "shirt"},
        {"item_id": "item_012", "description": "Denim jacket, blue wash, worn once", "category": "jacket"},
        {"item_id": "item_013", "description": "Red silk blouse, elegant evening wear", "category": "shirt"},
        {"item_id": "item_014", "description": "Brown suede boots, ankle height", "category": "shoes"},
        {"item_id": "item_015", "description": "Black wool coat, winter essential", "category": "jacket"},
        {"item_id": "item_016", "description": "Blue denim jacket, oversized fit", "category": "jacket"},
        {"item_id": "item_017", "description": "Green vintage dress, 1960s style", "category": "dress"},
        {"item_id": "item_018", "description": "Red leather purse, crossbody style", "category": "accessories"},
        {"item_id": "item_019", "description": "White sneakers, athletic style", "category": "shoes"},
        {"item_id": "item_020", "description": "Black cotton pants, professional fit", "category": "pants"},
    ]
    
    # Add image paths (placeholder - in production would point to actual images)
    assets_path = Path(__file__).parent / "assets" / "images"
    
    for item in sample_items:
        # In production, check if image exists
        # For MVP, we'll use None or placeholder paths
        image_path = assets_path / f"{item['item_id']}.jpg"
        item["image_path"] = str(image_path) if image_path.exists() else None
        
        # Add pre-computed embedding placeholder (would be loaded from file in production)
        item["embedding"] = None
    
    return pd.DataFrame(sample_items)


def get_sample_noisy_description() -> str:
    """
    Get a sample noisy description for testing
    Mimics typical Depop/Poshmark listings
    
    Returns:
        Sample noisy text description
    """
    samples = [
        "Cute top, worn once, vintage vibes",
        "Cool red denim jacket, button down front",
        "Black leather boots, excellent condition",
        "Vintage dress, needs some love",
        "Selling my fav jacket! Red denim, super cute",
        "Blue shirt, cotton, great condition",
        "Leather bag, used but still in good shape",
        "Jeans, worn a few times, like new",
        "Red vintage top, retro style, so cute",
        "Black blazer, formal wear, professional"
    ]
    
    return random.choice(samples)


def create_sample_catalog_embeddings(output_path: str = "catalog_embeddings.npy"):
    """
    Create sample pre-computed embeddings for catalog items
    In production, these would be generated by the actual model and saved
    
    Args:
        output_path: Path to save embeddings file
    """
    catalog_df = load_catalog()
    embedding_dim = 512
    
    embeddings = []
    for idx in range(len(catalog_df)):
        # In production, use actual model to generate embeddings
        embedding = np.random.RandomState(idx).randn(embedding_dim).astype(np.float32)
        embeddings.append(embedding)
    
    embeddings_array = np.vstack(embeddings)
    np.save(output_path, embeddings_array)
    
    return embeddings_array


def load_precomputed_embeddings(embeddings_path: str = "catalog_embeddings.npy") -> np.ndarray:
    """
    Load pre-computed embeddings for faster similarity search
    
    Args:
        embeddings_path: Path to embeddings file
        
    Returns:
        NumPy array of embeddings (N x embedding_dim)
    """
    embeddings_path = Path(embeddings_path)
    
    if embeddings_path.exists():
        return np.load(embeddings_path)
    else:
        # Generate if doesn't exist
        return create_sample_catalog_embeddings(str(embeddings_path))

